### ISSUE TITLE
Error - Help

### ISSUE THREAD

**Issue by trsilva32** [jonathanferreiras/whats-bot#8]
Jonathan,
Could you help me out?
I'm trying to run your code, but this error is coming up?

> AttributeError: 'ChatBot' object has no attribute 'train'

This refers to this part of the code:
`def treina(self, nome_pasta):`
........` for treino in os.listdir(nome_pasta):`
........`conversas = open(nome_pasta + '/' + treino, 'r').readlines()`
........`self.bot.train(conversas)`

tsk

**Comment by CELSORISSI** [comment]
Estou com erro ao localizar o selenium, mesmo ja tendo instalado corretamente pelo pip.
Parece que esta faltando argumento??

Comando:
from selenium import webdriver

Erro:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'selenium'
